# Generated by Django 4.1.1 on 2022-09-15 12:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.TextField(blank=True, unique=True, verbose_name='name of the dish')),
                ('dish_category', models.TextField(blank=True, verbose_name='type of dish')),
                ('dish_price', models.FloatField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price of the dish')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='id of the table')),
                ('table_people', models.PositiveIntegerField(default=0, verbose_name='number of people in the table')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restourant.dish')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restourant.table')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restourant.dish')),
            ],
        ),
    ]
