# Generated by Django 4.1.1 on 2022-09-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, verbose_name='datetime of payment')),
                ('price', models.FloatField(blank=True, verbose_name='price of one dinner/lunch')),
            ],
        ),
    ]
