# Generated by Django 4.1.1 on 2022-09-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0002_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='data',
            field=models.DateField(blank=True, verbose_name='datetime of payment'),
        ),
    ]
