# Generated by Django 4.1.1 on 2022-09-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0003_alter_balance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False, verbose_name='dish done by the kitchen'),
        ),
    ]
